var SIZE = 25;
var LINENUM = 19;
var GOBANHEIGHT = SIZE*(LINENUM-1);
var GOBANWIDTH = SIZE*(LINENUM-1);
var CANVASHEIGHT = GOBANHEIGHT + 2*SIZE;
var CANVASWIDTH = GOBANWIDTH + 2*SIZE;
var BACKGROUNDCOLOR = 'rgb(242, 193, 48)';
var BACKGROUNDFONT = '10px Sans-serif';
var COLORBLACK = '#000000';
var COLORWHITE = '#FFFFFF';
var STONECOLOR = [COLORBLACK, COLORWHITE]; 

var XOFFSET = 8;
var YOFFSET = 8;

var THIS;


